### ISSUE TITLE
parser error: relation member

### ISSUE THREAD

**Issue by tungli** [FelixStridsberg/vadeen_osm#9]
Just tried out this package for fun, unfortunately I got a `ParseError` when loading an .osm map
```
Error { repr: Simple(ParseError), message: Some("Line 4326: The \'type\' attribute contains invalid data \'relation\'.") }
```

The corresponding line is:
```xml
 <relation id="442084" visible="true" version="229" changeset="57893707" timestamp="2018-04-07T15:21:19Z" user="xificurk" uid="229590">
```
and this block later contains entries like:
```xml
<member type="relation" ref="442061" role="subarea"/>
```
which I suspect create this issue.

**Comment by tungli** [comment]
Changing the string `"rel"` to `"relation"` in xml/reader.rs seems to do the trick.

Here's the diff:
```diff
diff --git a/src/osm_io/xml/reader.rs b/src/osm_io/xml/reader.rs
index 9bbebe8..2486de6 100644
--- a/src/osm_io/xml/reader.rs
+++ b/src/osm_io/xml/reader.rs
@@ -156,7 +156,7 @@ impl Attributes {
         match mem_type.as_ref() {
             "node" => Ok(RelationMember::Node(mem_ref, mem_role.to_owned())),
             "way" => Ok(RelationMember::Way(mem_ref, mem_role.to_owned())),
-            "rel" => Ok(RelationMember::Relation(mem_ref, mem_role.to_owned())),
+            "relation" => Ok(RelationMember::Relation(mem_ref, mem_role.to_owned())),
             t => Err(Error::new(
                 ParseError,
                 Some(format!(
```

I am clueless on the specification of the `.osm` file, so I do not know if this is due to a version change or if both variants are acceptable.

**Comment by FelixStridsberg** [comment]
Hi, thank you for pointing this out!

Some of my tools generates the type as 'rel'. I can't find any clear documentation of this. openstreetmap.org exports it as 'relation'.

I've added 'relation' but kept 'rel' so it continues to work with my tools as well. Will publish a new version with this fix.

**Comment by FelixStridsberg** [comment]
Version 0.4.1 is now published and can handle this type name.
Thank you for contributing!
